### ISSUE TITLE
Cannot create time-based index patterns when using remote cluster indices [BUG]

### ISSUE THREAD

**Issue by verbecee** [opendistro-for-elasticsearch/index-management#418] opened 2021-03-16 20:36 UTC
Not sure if I should paste here or in the Kibana index management plugin repo.
**Describe the bug**
Context: We are moving from a single behemoth cluster to a multicluster architecture. The new architecture will consist of 3 remote clusters (spread across 3 AZs) and a coordinating cluster. The coordinating cluster is our behemoth cluster, so we have 180 TB of data on that cluster and are shrinking it down over time. Since we have data on our coordinating cluster AND in our indices on the 3 clusters, I need to create an index pattern that will span all 4 clusters. I can perform searches and this works:

GET /sample_index*,*:sample_index*/_search

When I go to create an index pattern, I am able to locate the indexes in the remote and coordinating clusters:
![image](https://user-images.githubusercontent.com/43911219/111376131-11048c00-866d-11eb-8d5a-ca67e8f15b0b.png)

When I hit "Next Step", I don't have the option to specify @timestamp as the time field.
 
![image](https://user-images.githubusercontent.com/43911219/111376189-224d9880-866d-11eb-8e37-dade6fb9e365.png)

This issue also occurs if I only have the remote cluster pattern set, too. I.e. all of these patterns also do not allow me to select a time field:

*:sample_index*
cluster_zone_a:sample_index*
cluster_zone_b:sample_index*
cluster_zone_c:sample_index*

This impacts all 150 index patterns, i.e. it isn't a single index issue. There is @timestamp in every log in the remote clusters. The index template as @timestamp defined as well. I added index templates via CURL to each remote cluster.
`
{
"order":2,
"index_patterns":[
"*log*"
],
"mappings":{
"_meta":{
"version":"1.7.0"
},
"date_detection":false,
"dynamic_templates":[
{
"strings_as_keyword":{
"mapping":{
"ignore_above":1024,
"type":"keyword"
},
"match_mapping_type":"string"
}
}
],
"properties":{
"@timestamp":{
"type":"date"
},
`

^ Note that this obviously isn't complete json.

Here is a sample log from the remote cluster, @timestamp is halfway down the log:

![image](https://user-images.githubusercontent.com/43911219/111376304-48733880-866d-11eb-8f8a-cbfb51173cf9.png)

**Other plugins installed*
Kibana reporting, security

**To Reproduce**
1. Add remote cluster (and connect it to the coordinating cluster)
2. Add data to remote cluster, with the field @timestamp as a part of the data
3. In coordinating cluster, try to create an index pattern

**Expected behavior**
Since @timestamp is present in each log in Elasticsearch, I would expect to be able to create time-based index patterns.

**Screenshots**
Added above.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 89.0

**Additional context**

**Other plugins installed*
Kibana reporting, security

**To Reproduce**
1. Add remote cluster (and connect it to the coordinating cluster)
2. Add data to remote cluster
3. In coordinating cluster, try to create an index pattern

**Expected behavior**
Since @timestamp is present in each log in Elasticsearch, I would expect to be able to create time-based index patterns.

**Screenshots**
Added.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 89.0

**Additional context**

**Comment by thalurur** [comment] 2021-03-16 21:55
@verbecee Will you be able to paste the response for this API?
``GET /<replace with the index pattern>/_field_caps?fields=@timestamp``

**Comment by bowenlan-amzn** [comment] 2021-03-16 23:38
I have seen user having similar issue, their index pattern matches ~4000 indices
Can you check if domain is overloaded? like too many indices or shards?

Also like Ravi mentioned above, similar command gets executed behind the scene to retrieve back all fields of index
So you can check kibana log to see if there is any related info, try grep your index pattern

**Comment by verbecee** [comment] 2021-03-17 13:48
Thank you both for the quick reply. 

@thalurur  here is the output - the bottom blue box is the coordinating cluster index.
![image](https://user-images.githubusercontent.com/43911219/111476746-718eda00-86fc-11eb-8e1b-80672423c5e4.png)

@bowenlan-amzn I have a few follow-up questions:

1. By "domain is overloaded," do you mean that we have too many shards? Yes, we have too many shards for our coordinating cluster. Our remote nodes are basically empty minus the couple thousand records in each index I had created.
2. If it isn't shard related, how would I check that my domain is overloaded otherwise?
3. You said, "try grep your index pattern" - is this the same thing as what thalurur asked above?

**Comment by verbecee** [comment] 2021-03-17 14:39
As a follow up, I tried a few more things:

1. I created an index on a remote cluster with two fields, @timestamp and message and added a doc with those fields defined. I couldn't create a time-based index pattern (TBIP - calling it this now for brevity hehe). I did this to confirm that all documents in an index have the @timestamp field.
2. I also tried toggling the "date_detection" key in the index template. I tried turning it to false and true, and still could not create a TBIP. Almost all of our indexes have that field set to false in production.

**Comment by brian-grabau** [comment] 2021-03-17 15:42
We created these remote clusters to extend our capacity, we have not set up and are not doing replication.

**Comment by thalurur** [comment] 2021-03-18 16:35
Tagging the kibana team to take a look - @mihirsoni @seraphjiang @zengyan-amazon 

We had an offline sync up even though the issue is currently residing in the IndexManagement repo, it doesn't seem to be an issue with the IM plugin. The issue seems to be either with kibana or security configuration.

It would be good to confirm following 
* If kibana team can confirm that it is possible to create index pattern that contains a timestamp field on a cross cluster setup * If above is confirmed are there any security permissions needed to achieve the above

**Comment by hsiang9431-amzn** [comment] 2021-03-19 01:58
Hi, my team maintains the security plugin and I looked into this issue and designed following experiment:

1. Create 3 local clusters
2. Install plugins on these clusters
3. Add sample data to two of which, call them `cluster_one` and `cluster_two`
4. Configure the remaining cluster as the coordinating cluster, let's call it `main-clester`
5. Try to create index patterns on `main-clester` with patterns `cluster_one:kib*` and `cluster_two:kib*`
6. Observe the capability to create index with timestamps recognized by `main-clester`

Described steps are done with 2 plugin configurations:
- Install only `security` plugin
- Install both `job scheduler` and `index management` plugins

The observation is as listed:
Plugin configuration | Step 6 succeed
---------|----------
`security` plugin only | 🟢 Yes
`job scheduler` and `index management` plugins | 🔴 No

Conclusion inferred from the observation: It is unlikely this issue is caused by `security` plugin or configuration regarding it.
Reasoning: The bug is observable when `security` plugin is not installed on the system

Please feel free to reach out and I can provide help for recreating the testing environment.

Thanks,

**Comment by brian-grabau** [comment] 2021-03-19 13:10
Were you able to create index patterns for indexes on remote clusters and where you able to select primary time field?

**Comment by verbecee** [comment] 2021-03-19 13:30
So it sounds like it is not a permissions issue, but something in the job scheduler or index management plugins. It's nice to confirm that we can at least create time-based index patterns, but there's something blocking it. @thalurur or @bowenlan-amzn are you guys the correct team to pass it back to?

**Comment by verbecee** [comment] 2021-03-19 13:47
We are going to try rolling our own dev cluster without job scheduler and index management (and then try one on, one off) to see if we see the same problem.

**Comment by hsiang9431-amzn** [comment] 2021-03-19 18:12
> So it sounds like it is not a permissions issue, but something in the job scheduler or index management plugins. It's nice to confirm that we can at least create time-based index patterns, but there's something blocking it. hsiang9431-amzn, are you able to engage the right teams?

I believe @thalurur and @bowenlan-amzn in the previous posts are the person to contact.

**Comment by verbecee** [comment] 2021-03-22 19:12
Hi everyone - we removed the index management plugin in our dev cluster and were able to create TBIP. We removed it on our kibana, coordinating cluster, and all remote clusters. We're going to try adding back the plugin to our coordinating cluster and see if the issue persists.

**Comment by dbbaughe** [comment] 2021-03-22 19:30
Hey @verbecee, are you using the rollup feature?

**Comment by verbecee** [comment] 2021-03-22 19:31
Nope, we are not @dbbaughe

**Comment by brian-grabau** [comment] 2021-03-22 19:58
Nope because it does not meet our needs, I think we may however create our own… (when we get time)

Brian Grabau
Information Security Engineering Advisor – TGRC
Cargill Command Center
Cargill
Helping the world thrive
direct: 952-984-4820 cell: 952-290-3221
Cargill Command Center / 9320 Excelsior Boulevard / Hopkins, MN 55343

Confidentiality Note: This message is intended only for the named recipient and may contain confidential, proprietary or legally privileged information. Unauthorized individuals or entities are not permitted access to this information. Any dissemination, distribution, or copying of this information is strictly prohibited. If you have received this message in error, please advise the sender by reply e-mail, and delete this message and any attachments. Thank you.

**Comment by dbbaughe** [comment] 2021-03-22 20:49
@verbecee 
@brian-grabau 
Got it, was just thinking that would be the most likely culprit. There is an action filter that intercepts FieldCapabilitiesRequests and does some extra processing for rollups.

https://github.com/opendistro-for-elasticsearch/index-management/blob/main/src/main/kotlin/com/amazon/opendistroforelasticsearch/indexmanagement/rollup/actionfilter/FieldCapsFilter.kt#L58-L74

But, if there are no rollup indices found in the request it should be skipping this and just proceeding with the chain.

I think we'll just have to do some testing on our end to see where this is happening in Index Management since it's pointing back to this again.

**Comment by KrishnanandSingh** [comment] 2021-03-23 13:13
I did a thorough testing and it turns out that the Index management plugin needs to be removed from only **kibana cluster** and **elastic** running on kibana nodes
Elastic on remote cluster and on coordinating cluster may continue to have all the plugins and cross cluster index pattern creation still works.

**Comment by brian-grabau** [comment] 2021-03-23 13:52
Quick note on setup, elastic coordinating only node installed in Kibana  server(s) on the coordinating cluster and Kibana is pointed this local node directly

**Comment by thalurur** [comment] 2021-03-24 02:24
I was able to confirm the root cause of the issue is the interception we are doing in IndexManagement for ``field_caps`` API. As part of interception we try to resolve the indices requested in the ``field_caps`` to concrete indices and if a remote cluster index is used then the index resolver is throwing ``IndexNotFoundException`` at the moment. 

https://github.com/opendistro-for-elasticsearch/index-management/blob/main/src/main/kotlin/com/amazon/opendistroforelasticsearch/indexmanagement/rollup/actionfilter/FieldCapsFilter.kt#L60

**Comment by brian-grabau** [comment] 2021-03-29 15:53
Did you want us to cover our site in an opendistro user group? We need to add some documentation to the site and need lead time to create slide deck.

OpenSIEM-Logstash-Parsing/settings.json at master · Cargill/OpenSIEM-Logstash-Parsing (github.com)<https://github.com/Cargill/OpenSIEM-Logstash-Parsing>


Brian Grabau
Information Security Engineering Advisor – TGRC
Cargill Command Center
Cargill
Helping the world thrive
direct: 952-984-4820 cell: 952-290-3221
Cargill Command Center / 9320 Excelsior Boulevard / Hopkins, MN 55343

Confidentiality Note: This message is intended only for the named recipient and may contain confidential, proprietary or legally privileged information. Unauthorized individuals or entities are not permitted access to this information. Any dissemination, distribution, or copying of this information is strictly prohibited. If you have received this message in error, please advise the sender by reply e-mail, and delete this message and any attachments. Thank you.

**Comment by thalurur** [comment] 2021-04-07 22:35
The fix is released as part of 1.13.2 - https://github.com/opendistro-for-elasticsearch/index-management/releases/tag/v1.13.2.0

**Comment by verbecee** [comment] 2021-04-12 20:23
Thank you so much!!

**Closed** 2021-05-04 17:54 UTC
Labels: bug
